Pawelka/proto
davidfowl/Sockets pull request #6
Opened 2016-10-06 00:05 UTC by moozzyk

2016-10-26 00:39 UTC, moozzyk commented
:up::date:

2016-10-26 06:58 UTC, davidfowl requested changes

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/EndPoints/ChatEndPoint.cs
> +        public ChatEndPoint()
Dead code?

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/EndPoints/HubEndpoint.cs
> +                    var invocationAdapter = _endPoint._serviceProvider.GetRequiredService<InvocationAdapterRegistry>()
nit: Split this into 2 lines (the call to `GetRequiredService<InvocationAdapterRegistry>()`)

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/EndPoints/HubEndpoint.cs
> +                var invocationAdapter = _endPoint._serviceProvider.GetRequiredService<InvocationAdapterRegistry>()
Same nit: as above

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/EndPoints/RpcEndpoint.cs
> +                                return _paramTypes.TryGetValue(methodName, out types) ? types : null;
I don't love this.

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/IInvocationAdapter.cs
> +        Task WriteInvocationResult(Stream stream, InvocationResultDescriptor resultDescriptor);
Arguments should be swapped.

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/IInvocationAdapter.cs
> +        Task<InvocationDescriptor> CreateInvocationDescriptor(Stream stream, Func<string, Type[]> getParams);
Should this be ReadInvocationDescriptor?

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/JSonInvocationAdapter.cs
> +    public class JSonInvocationAdapter : IInvocationAdapter
nit: Casing. `JsonInvocationAdapter`

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/JSonInvocationAdapter.cs
> +            return await Task.Run(() => _serializer.Deserialize<InvocationDescriptor>(reader));
Part of me wants to expose the channel API here so we can just read async here...

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/Protobuf/ProtobufInvocationAdapter.cs
> +        IServiceProvider _serviceProvider;
nit: private 😄

2016-10-26 06:58 UTC, davidfowl commented on samples/SocketsSample/Protobuf/ProtobufInvocationAdapter.cs
> +                }
else throw?

2016-10-26 06:58 UTC, davidfowl commented on src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs
> +                    // TODO: this is wrong. + how does the user add their own metadata based on HttpContext
We need a service for this since it's http host specific.

2016-10-26 06:58 UTC, davidfowl commented on src/Microsoft.AspNetCore.Sockets/HttpDispatcherAppBuilderExtensions.cs
> +
nit: space

2016-10-26 06:58 UTC, davidfowl commented on src/Microsoft.AspNetCore.Sockets/WebSockets.cs
> +            _messageType = format == Format.Binary ? WebSocketMessageType.Binary : WebSocketMessageType.Text;
Is this for outgoing only?

2016-10-26 17:36 UTC, moozzyk commented on samples/SocketsSample/IInvocationAdapter.cs
> +        Task<InvocationDescriptor> CreateInvocationDescriptor(Stream stream, Func<string, Type[]> getParams);
Sure.

2016-10-26 17:53 UTC, moozzyk commented on samples/SocketsSample/Protobuf/ProtobufInvocationAdapter.cs
> +                }
No. Invoke custom serialization. (updated)

2016-10-26 18:08 UTC, moozzyk commented on src/Microsoft.AspNetCore.Sockets/WebSockets.cs
> +            _messageType = format == Format.Binary ? WebSocketMessageType.Binary : WebSocketMessageType.Text;
Yes. On the way in we consume the stream. I actually talked to @tratcher about this and he said that mode actually does not matter as much - we could always just use binary. Apparently setting message type to .Text just introduces some additional checks on the data being sent (and what receive callback/overload on the client side is invoked). So maybe we can just drop this.

2016-10-26 19:01 UTC, moozzyk commented on samples/SocketsSample/EndPoints/RpcEndpoint.cs
> +                                return _paramTypes.TryGetValue(methodName, out types) ? types : null;
Any specifics?

2016-10-26 19:05 UTC, moozzyk commented on samples/SocketsSample/IInvocationAdapter.cs
> +        Task WriteInvocationResult(Stream stream, InvocationResultDescriptor resultDescriptor);
OK, but why?

2016-10-26 19:05 UTC, moozzyk commented on src/Microsoft.AspNetCore.Sockets/HttpConnectionDispatcher.cs
> +                    // TODO: this is wrong. + how does the user add their own metadata based on HttpContext
Leaving as is now.

2016-10-27 03:48 UTC, davidfowl commented on src/Microsoft.AspNetCore.Sockets/WebSockets.cs
> +            _messageType = format == Format.Binary ? WebSocketMessageType.Binary : WebSocketMessageType.Text;
Interesting

2016-10-27 03:51 UTC, davidfowl commented on samples/SocketsSample/Protobuf/ProtobufInvocationAdapter.cs
> +                }
ah

2016-10-27 03:52 UTC, davidfowl approved these changes
This is a good first pass! Let's commit and rev

2016-10-27 16:31 UTC, closed without merging